### ISSUE TITLE
qdrant docker-compose

### ISSUE THREAD

**Issue by patbhakta** [technovangelist/homelab#3]
```
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - ./qdrant-data:/qdrant/storage
    env_file:
      - .env
    environment:
      # Optional: Set QDRANT__SERVICE__HTTP_PORT if you want to change the default port (6333)
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      # Optional: Enable telemetry (set to false to disable)
      - QDRANT__TELEMETRY_DISABLED=false
      # Optional: Set log level
      - QDRANT__LOG_LEVEL=INFO
    # Expose ports for local development (remove if only using Tailscale)
    # ports:
    #   - "6333:6333"  # REST API
    #   - "6334:6334"  # gRPC API
    network_mode: service:qdrant-on-hstgr
    
  qdrant-on-hstgr:
    image: tailscale/tailscale:latest
    hostname: qdrant-on-hstgr
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-qdrant/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    secrets:
      - tsauthkey

secrets:
  tsauthkey:
    file: ~/.config/tsauthkey
```
